spring:
  application:
    name: lottery
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lottery?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&remarks=true&useInformationSchema=true&allowPublicKeyRetrieval=true
    username: root
    password: LoL@20201112
  ai:
#    dashscope:
#      api-key: sk-d25302429c494d70b9c36f027db09108 # 阿里云百炼大模型
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      chat:
#        options:
#          model: qwen3-max
    ollama:
      base-url: http://localhost:11434
      chat:
#        model: qwen3-vl:30b
        model: gpt-oss:120b

server:
  port: 8888
